### ISSUE TITLE
AI names in chat are read as "the (AI name)" rather than "(ai name)"

### ISSUE THREAD

**Issue by OmegaDarkPotato** [DopplerShift13/DopplerShift#219]
### Client Version:

515.1637

### Issue Summary:

When I send a message in chat as Brightspar, I see `[Common] The brightspar@f52e8d (AI)` rather than what I should be seeing of `[Common] brightspar@f52e8d (AI)`. Not sure what's causing this.

### Round ID:

[261](https://scrubby.melonmesa.com/round/261)

### Reproduction Steps:

Spawn in as AI, talk over comms, see "the (your ai name here)" while everyone else is just "(their name)".

**Comment by tiramisuapimancer** [comment]
its not because of ai, its because your name started with a lowercase

**Comment by OmegaDarkPotato** [comment]
DESPAIR. oh well, headcanon naming convention's gotta get moved aside then
