### ISSUE TITLE
Ghostroles without specified required species are unable to be spawned in

### ISSUE THREAD

**Issue by CliffracerX** [DopplerShift13/DopplerShift#90]
### Client Version:

515.1637

### Issue Summary:

Try to spawn in as a ghostrole, fail for having a non-null species (?)
![image](https://github.com/user-attachments/assets/fb62911e-c138-4a12-8b4a-9c9cf2b12b0d)

### Round ID:

[29](https://scrubby.melonmesa.com/round/29)

### Test Merge Information:

Server revision compiled on: 2024-09-23T21:01:59+00:00
Master commit: [6d7ed4e3e62ed0074f617a800dd3f1da59414973](https://github.com/DopplerShift13/DopplerShift/commit/6d7ed4e3e62ed0074f617a800dd3f1da59414973)
The following pull requests are currently test merged:
[#64: 'Roleplay essentials: flavor text & records' by Ephemeralis at commit 399bcd6e33](https://github.com/DopplerShift13/DopplerShift/pull/64)

### Reproduction Steps:

1. Go to a ghostrole (e.g, syndie ship captain, abandoned station)
2. Try to spawn
3. Don't spawn :(

**Comment by honkpocket** [comment]
Fixed in https://github.com/DopplerShift13/DopplerShift/pull/92.
